// Code generated by lesiw.io/moxie. DO NOT EDIT.

package testdata

import (
	pkg "lesiw.io/moxie/internal/testdata/pkg"
	runtime "runtime"
	sync "sync"
	unsafe "unsafe"
)

var _M0 = new(sync.Map)

type _M0Data struct {
	mutex sync.Mutex
	once sync.Once
	AllNamedIdentifiersMocks []func(x pkg.String, y ...pkg.String) (n pkg.Int, err error)
	AllNamedIdentifiersCalls []_M0_AllNamedIdentifiers_Call
	MixedNoResultMocks []func(pkg.String, ...pkg.String)
	MixedNoResultCalls []_M0_MixedNoResult_Call
	MixedOneResultMocks []func(pkg.String, ...pkg.String) error
	MixedOneResultCalls []_M0_MixedOneResult_Call
	MixedTwoResultsMocks []func(pkg.String, ...pkg.String) (pkg.Int, error)
	MixedTwoResultsCalls []_M0_MixedTwoResults_Call
	NamedMixedNoResultMocks []func(x pkg.String, y ...pkg.String)
	NamedMixedNoResultCalls []_M0_NamedMixedNoResult_Call
	NamedMixedOneResultMocks []func(x pkg.String, y ...pkg.String) error
	NamedMixedOneResultCalls []_M0_NamedMixedOneResult_Call
	NamedMixedTwoResultsMocks []func(x pkg.String, y ...pkg.String) (pkg.Int, error)
	NamedMixedTwoResultsCalls []_M0_NamedMixedTwoResults_Call
	NamedParamNoResultMocks []func(x pkg.String)
	NamedParamNoResultCalls []_M0_NamedParamNoResult_Call
	NamedParamOneResultMocks []func(x pkg.String) error
	NamedParamOneResultCalls []_M0_NamedParamOneResult_Call
	NamedParamTwoResultsMocks []func(x pkg.String) (pkg.Int, error)
	NamedParamTwoResultsCalls []_M0_NamedParamTwoResults_Call
	OneNamedResultMocks []func() (err error)
	OneNamedResultCalls []_M0_OneNamedResult_Call
	OneParamNoResultMocks []func(pkg.String)
	OneParamNoResultCalls []_M0_OneParamNoResult_Call
	OneParamOneResultMocks []func(pkg.String) error
	OneParamOneResultCalls []_M0_OneParamOneResult_Call
	OneParamTwoResultsMocks []func(pkg.String) (pkg.Int, error)
	OneParamTwoResultsCalls []_M0_OneParamTwoResults_Call
	OneResultMocks []func() error
	OneResultCalls []_M0_OneResult_Call
	SimpleMocks []func()
	SimpleCalls []_M0_Simple_Call
	TwoNamedResultsMocks []func() (n pkg.Int, err error)
	TwoNamedResultsCalls []_M0_TwoNamedResults_Call
	TwoParamsNoResultMocks []func(pkg.String, pkg.String)
	TwoParamsNoResultCalls []_M0_TwoParamsNoResult_Call
	TwoParamsOneResultMocks []func(pkg.String, pkg.String) error
	TwoParamsOneResultCalls []_M0_TwoParamsOneResult_Call
	TwoParamsTwoResultsMocks []func(pkg.String, pkg.String) (pkg.Int, error)
	TwoParamsTwoResultsCalls []_M0_TwoParamsTwoResults_Call
	TwoResultsMocks []func() (pkg.Int, error)
	TwoResultsCalls []_M0_TwoResults_Call
	VariadicNoResultMocks []func(...pkg.String)
	VariadicNoResultCalls []_M0_VariadicNoResult_Call
	VariadicOneResultMocks []func(...pkg.String) error
	VariadicOneResultCalls []_M0_VariadicOneResult_Call
	VariadicTwoResultsMocks []func(...pkg.String) (pkg.Int, error)
	VariadicTwoResultsCalls []_M0_VariadicTwoResults_Call
}

func _M0PtrData(t *M0) *_M0Data {
	ptr := uintptr(unsafe.Pointer(t))
	val, loaded := _M0.LoadOrStore(ptr, new(_M0Data))
	if !loaded {
		val.(*_M0Data).once.Do(func() { runtime.SetFinalizer(t, func(_ *M0) { _M0.Delete(ptr) })})
	}
	return val.(*_M0Data)
}

type _M0_AllNamedIdentifiers_Call struct {
	X pkg.String
	Y []pkg.String
}
type _M0_MixedNoResult_Call struct {
	P0 pkg.String
	P1 []pkg.String
}
type _M0_MixedOneResult_Call struct {
	P0 pkg.String
	P1 []pkg.String
}
type _M0_MixedTwoResults_Call struct {
	P0 pkg.String
	P1 []pkg.String
}
type _M0_NamedMixedNoResult_Call struct {
	X pkg.String
	Y []pkg.String
}
type _M0_NamedMixedOneResult_Call struct {
	X pkg.String
	Y []pkg.String
}
type _M0_NamedMixedTwoResults_Call struct {
	X pkg.String
	Y []pkg.String
}
type _M0_NamedParamNoResult_Call struct {
	X pkg.String
}
type _M0_NamedParamOneResult_Call struct {
	X pkg.String
}
type _M0_NamedParamTwoResults_Call struct {
	X pkg.String
}
type _M0_OneNamedResult_Call struct {}
type _M0_OneParamNoResult_Call struct {
	P0 pkg.String
}
type _M0_OneParamOneResult_Call struct {
	P0 pkg.String
}
type _M0_OneParamTwoResults_Call struct {
	P0 pkg.String
}
type _M0_OneResult_Call struct {}
type _M0_Simple_Call struct {}
type _M0_TwoNamedResults_Call struct {}
type _M0_TwoParamsNoResult_Call struct {
	P0 pkg.String
	P1 pkg.String
}
type _M0_TwoParamsOneResult_Call struct {
	P0 pkg.String
	P1 pkg.String
}
type _M0_TwoParamsTwoResults_Call struct {
	P0 pkg.String
	P1 pkg.String
}
type _M0_TwoResults_Call struct {}
type _M0_VariadicNoResult_Call struct {
	P0 []pkg.String
}
type _M0_VariadicOneResult_Call struct {
	P0 []pkg.String
}
type _M0_VariadicTwoResults_Call struct {
	P0 []pkg.String
}

func (_recv *M0) AllNamedIdentifiers(X pkg.String, Y ...pkg.String) (pkg.Int, error) {
	if _recv == nil {
		panic("M0.AllNamedIdentifiers: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	_dat.mutex.Lock()
	_dat.AllNamedIdentifiersCalls = append(_dat.AllNamedIdentifiersCalls, _M0_AllNamedIdentifiers_Call{X, Y})
	_fn := _recv.T0.AllNamedIdentifiers
	if len(_dat.AllNamedIdentifiersMocks) > 0 {
		_fn = _dat.AllNamedIdentifiersMocks[0]
		if len(_dat.AllNamedIdentifiersMocks) > 1 {
			_dat.AllNamedIdentifiersMocks = _dat.AllNamedIdentifiersMocks[1:]
		}
	}
	_dat.mutex.Unlock()
	return _fn(X, Y...)
}

func (_recv *M0) _AllNamedIdentifiers_Do(fn func(pkg.String, ...pkg.String) (pkg.Int, error)) {
	if _recv == nil {
		panic("M0.AllNamedIdentifiers: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	if fn == nil {
		_dat.AllNamedIdentifiersMocks = []func(pkg.String, ...pkg.String) (pkg.Int, error){}
	} else if len(_dat.AllNamedIdentifiersMocks) < 2 {
		_dat.AllNamedIdentifiersMocks = []func(pkg.String, ...pkg.String) (pkg.Int, error){fn, fn}
	} else {
		_dat.AllNamedIdentifiersMocks = _dat.AllNamedIdentifiersMocks[:len(_dat.AllNamedIdentifiersMocks)-1]
		_dat.AllNamedIdentifiersMocks = append(_dat.AllNamedIdentifiersMocks, fn)
		_dat.AllNamedIdentifiersMocks = append(_dat.AllNamedIdentifiersMocks, fn)
	}
}

func (_recv *M0) _AllNamedIdentifiers_Stub() {
	_recv._AllNamedIdentifiers_Do(func(pkg.String, ...pkg.String) (n pkg.Int, err error) {
		return n, err
	})
}

func (_recv *M0) _AllNamedIdentifiers_Return(n pkg.Int, err error) {
	_recv._AllNamedIdentifiers_Do(func(pkg.String, ...pkg.String) (pkg.Int, error) {
		return n, err
	})
}

func (_recv *M0) _AllNamedIdentifiers_Calls() []_M0_AllNamedIdentifiers_Call {
	if _recv == nil {
		panic("M0.AllNamedIdentifiers: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	return _dat.AllNamedIdentifiersCalls
}

func (_recv *M0) MixedNoResult(P0 pkg.String, P1 ...pkg.String) {
	if _recv == nil {
		panic("M0.MixedNoResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	_dat.mutex.Lock()
	_dat.MixedNoResultCalls = append(_dat.MixedNoResultCalls, _M0_MixedNoResult_Call{P0, P1})
	_fn := _recv.T0.MixedNoResult
	if len(_dat.MixedNoResultMocks) > 0 {
		_fn = _dat.MixedNoResultMocks[0]
		if len(_dat.MixedNoResultMocks) > 1 {
			_dat.MixedNoResultMocks = _dat.MixedNoResultMocks[1:]
		}
	}
	_dat.mutex.Unlock()
	_fn(P0, P1...)
}

func (_recv *M0) _MixedNoResult_Do(fn func(pkg.String, ...pkg.String) ()) {
	if _recv == nil {
		panic("M0.MixedNoResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	if fn == nil {
		_dat.MixedNoResultMocks = []func(pkg.String, ...pkg.String) (){}
	} else if len(_dat.MixedNoResultMocks) < 2 {
		_dat.MixedNoResultMocks = []func(pkg.String, ...pkg.String) (){fn, fn}
	} else {
		_dat.MixedNoResultMocks = _dat.MixedNoResultMocks[:len(_dat.MixedNoResultMocks)-1]
		_dat.MixedNoResultMocks = append(_dat.MixedNoResultMocks, fn)
		_dat.MixedNoResultMocks = append(_dat.MixedNoResultMocks, fn)
	}
}

func (_recv *M0) _MixedNoResult_Stub() {
	_recv._MixedNoResult_Do(func(pkg.String, ...pkg.String) () {
		return 
	})
}

func (_recv *M0) _MixedNoResult_Return() {
	_recv._MixedNoResult_Do(func(pkg.String, ...pkg.String) () {
		return 
	})
}

func (_recv *M0) _MixedNoResult_Calls() []_M0_MixedNoResult_Call {
	if _recv == nil {
		panic("M0.MixedNoResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	return _dat.MixedNoResultCalls
}

func (_recv *M0) MixedOneResult(P0 pkg.String, P1 ...pkg.String) error {
	if _recv == nil {
		panic("M0.MixedOneResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	_dat.mutex.Lock()
	_dat.MixedOneResultCalls = append(_dat.MixedOneResultCalls, _M0_MixedOneResult_Call{P0, P1})
	_fn := _recv.T0.MixedOneResult
	if len(_dat.MixedOneResultMocks) > 0 {
		_fn = _dat.MixedOneResultMocks[0]
		if len(_dat.MixedOneResultMocks) > 1 {
			_dat.MixedOneResultMocks = _dat.MixedOneResultMocks[1:]
		}
	}
	_dat.mutex.Unlock()
	return _fn(P0, P1...)
}

func (_recv *M0) _MixedOneResult_Do(fn func(pkg.String, ...pkg.String) (error)) {
	if _recv == nil {
		panic("M0.MixedOneResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	if fn == nil {
		_dat.MixedOneResultMocks = []func(pkg.String, ...pkg.String) (error){}
	} else if len(_dat.MixedOneResultMocks) < 2 {
		_dat.MixedOneResultMocks = []func(pkg.String, ...pkg.String) (error){fn, fn}
	} else {
		_dat.MixedOneResultMocks = _dat.MixedOneResultMocks[:len(_dat.MixedOneResultMocks)-1]
		_dat.MixedOneResultMocks = append(_dat.MixedOneResultMocks, fn)
		_dat.MixedOneResultMocks = append(_dat.MixedOneResultMocks, fn)
	}
}

func (_recv *M0) _MixedOneResult_Stub() {
	_recv._MixedOneResult_Do(func(pkg.String, ...pkg.String) (r0 error) {
		return r0
	})
}

func (_recv *M0) _MixedOneResult_Return(r0 error) {
	_recv._MixedOneResult_Do(func(pkg.String, ...pkg.String) (error) {
		return r0
	})
}

func (_recv *M0) _MixedOneResult_Calls() []_M0_MixedOneResult_Call {
	if _recv == nil {
		panic("M0.MixedOneResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	return _dat.MixedOneResultCalls
}

func (_recv *M0) MixedTwoResults(P0 pkg.String, P1 ...pkg.String) (pkg.Int, error) {
	if _recv == nil {
		panic("M0.MixedTwoResults: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	_dat.mutex.Lock()
	_dat.MixedTwoResultsCalls = append(_dat.MixedTwoResultsCalls, _M0_MixedTwoResults_Call{P0, P1})
	_fn := _recv.T0.MixedTwoResults
	if len(_dat.MixedTwoResultsMocks) > 0 {
		_fn = _dat.MixedTwoResultsMocks[0]
		if len(_dat.MixedTwoResultsMocks) > 1 {
			_dat.MixedTwoResultsMocks = _dat.MixedTwoResultsMocks[1:]
		}
	}
	_dat.mutex.Unlock()
	return _fn(P0, P1...)
}

func (_recv *M0) _MixedTwoResults_Do(fn func(pkg.String, ...pkg.String) (pkg.Int, error)) {
	if _recv == nil {
		panic("M0.MixedTwoResults: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	if fn == nil {
		_dat.MixedTwoResultsMocks = []func(pkg.String, ...pkg.String) (pkg.Int, error){}
	} else if len(_dat.MixedTwoResultsMocks) < 2 {
		_dat.MixedTwoResultsMocks = []func(pkg.String, ...pkg.String) (pkg.Int, error){fn, fn}
	} else {
		_dat.MixedTwoResultsMocks = _dat.MixedTwoResultsMocks[:len(_dat.MixedTwoResultsMocks)-1]
		_dat.MixedTwoResultsMocks = append(_dat.MixedTwoResultsMocks, fn)
		_dat.MixedTwoResultsMocks = append(_dat.MixedTwoResultsMocks, fn)
	}
}

func (_recv *M0) _MixedTwoResults_Stub() {
	_recv._MixedTwoResults_Do(func(pkg.String, ...pkg.String) (r0 pkg.Int, r1 error) {
		return r0, r1
	})
}

func (_recv *M0) _MixedTwoResults_Return(r0 pkg.Int, r1 error) {
	_recv._MixedTwoResults_Do(func(pkg.String, ...pkg.String) (pkg.Int, error) {
		return r0, r1
	})
}

func (_recv *M0) _MixedTwoResults_Calls() []_M0_MixedTwoResults_Call {
	if _recv == nil {
		panic("M0.MixedTwoResults: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	return _dat.MixedTwoResultsCalls
}

func (_recv *M0) NamedMixedNoResult(X pkg.String, Y ...pkg.String) {
	if _recv == nil {
		panic("M0.NamedMixedNoResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	_dat.mutex.Lock()
	_dat.NamedMixedNoResultCalls = append(_dat.NamedMixedNoResultCalls, _M0_NamedMixedNoResult_Call{X, Y})
	_fn := _recv.T0.NamedMixedNoResult
	if len(_dat.NamedMixedNoResultMocks) > 0 {
		_fn = _dat.NamedMixedNoResultMocks[0]
		if len(_dat.NamedMixedNoResultMocks) > 1 {
			_dat.NamedMixedNoResultMocks = _dat.NamedMixedNoResultMocks[1:]
		}
	}
	_dat.mutex.Unlock()
	_fn(X, Y...)
}

func (_recv *M0) _NamedMixedNoResult_Do(fn func(pkg.String, ...pkg.String) ()) {
	if _recv == nil {
		panic("M0.NamedMixedNoResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	if fn == nil {
		_dat.NamedMixedNoResultMocks = []func(pkg.String, ...pkg.String) (){}
	} else if len(_dat.NamedMixedNoResultMocks) < 2 {
		_dat.NamedMixedNoResultMocks = []func(pkg.String, ...pkg.String) (){fn, fn}
	} else {
		_dat.NamedMixedNoResultMocks = _dat.NamedMixedNoResultMocks[:len(_dat.NamedMixedNoResultMocks)-1]
		_dat.NamedMixedNoResultMocks = append(_dat.NamedMixedNoResultMocks, fn)
		_dat.NamedMixedNoResultMocks = append(_dat.NamedMixedNoResultMocks, fn)
	}
}

func (_recv *M0) _NamedMixedNoResult_Stub() {
	_recv._NamedMixedNoResult_Do(func(pkg.String, ...pkg.String) () {
		return 
	})
}

func (_recv *M0) _NamedMixedNoResult_Return() {
	_recv._NamedMixedNoResult_Do(func(pkg.String, ...pkg.String) () {
		return 
	})
}

func (_recv *M0) _NamedMixedNoResult_Calls() []_M0_NamedMixedNoResult_Call {
	if _recv == nil {
		panic("M0.NamedMixedNoResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	return _dat.NamedMixedNoResultCalls
}

func (_recv *M0) NamedMixedOneResult(X pkg.String, Y ...pkg.String) error {
	if _recv == nil {
		panic("M0.NamedMixedOneResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	_dat.mutex.Lock()
	_dat.NamedMixedOneResultCalls = append(_dat.NamedMixedOneResultCalls, _M0_NamedMixedOneResult_Call{X, Y})
	_fn := _recv.T0.NamedMixedOneResult
	if len(_dat.NamedMixedOneResultMocks) > 0 {
		_fn = _dat.NamedMixedOneResultMocks[0]
		if len(_dat.NamedMixedOneResultMocks) > 1 {
			_dat.NamedMixedOneResultMocks = _dat.NamedMixedOneResultMocks[1:]
		}
	}
	_dat.mutex.Unlock()
	return _fn(X, Y...)
}

func (_recv *M0) _NamedMixedOneResult_Do(fn func(pkg.String, ...pkg.String) (error)) {
	if _recv == nil {
		panic("M0.NamedMixedOneResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	if fn == nil {
		_dat.NamedMixedOneResultMocks = []func(pkg.String, ...pkg.String) (error){}
	} else if len(_dat.NamedMixedOneResultMocks) < 2 {
		_dat.NamedMixedOneResultMocks = []func(pkg.String, ...pkg.String) (error){fn, fn}
	} else {
		_dat.NamedMixedOneResultMocks = _dat.NamedMixedOneResultMocks[:len(_dat.NamedMixedOneResultMocks)-1]
		_dat.NamedMixedOneResultMocks = append(_dat.NamedMixedOneResultMocks, fn)
		_dat.NamedMixedOneResultMocks = append(_dat.NamedMixedOneResultMocks, fn)
	}
}

func (_recv *M0) _NamedMixedOneResult_Stub() {
	_recv._NamedMixedOneResult_Do(func(pkg.String, ...pkg.String) (r0 error) {
		return r0
	})
}

func (_recv *M0) _NamedMixedOneResult_Return(r0 error) {
	_recv._NamedMixedOneResult_Do(func(pkg.String, ...pkg.String) (error) {
		return r0
	})
}

func (_recv *M0) _NamedMixedOneResult_Calls() []_M0_NamedMixedOneResult_Call {
	if _recv == nil {
		panic("M0.NamedMixedOneResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	return _dat.NamedMixedOneResultCalls
}

func (_recv *M0) NamedMixedTwoResults(X pkg.String, Y ...pkg.String) (pkg.Int, error) {
	if _recv == nil {
		panic("M0.NamedMixedTwoResults: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	_dat.mutex.Lock()
	_dat.NamedMixedTwoResultsCalls = append(_dat.NamedMixedTwoResultsCalls, _M0_NamedMixedTwoResults_Call{X, Y})
	_fn := _recv.T0.NamedMixedTwoResults
	if len(_dat.NamedMixedTwoResultsMocks) > 0 {
		_fn = _dat.NamedMixedTwoResultsMocks[0]
		if len(_dat.NamedMixedTwoResultsMocks) > 1 {
			_dat.NamedMixedTwoResultsMocks = _dat.NamedMixedTwoResultsMocks[1:]
		}
	}
	_dat.mutex.Unlock()
	return _fn(X, Y...)
}

func (_recv *M0) _NamedMixedTwoResults_Do(fn func(pkg.String, ...pkg.String) (pkg.Int, error)) {
	if _recv == nil {
		panic("M0.NamedMixedTwoResults: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	if fn == nil {
		_dat.NamedMixedTwoResultsMocks = []func(pkg.String, ...pkg.String) (pkg.Int, error){}
	} else if len(_dat.NamedMixedTwoResultsMocks) < 2 {
		_dat.NamedMixedTwoResultsMocks = []func(pkg.String, ...pkg.String) (pkg.Int, error){fn, fn}
	} else {
		_dat.NamedMixedTwoResultsMocks = _dat.NamedMixedTwoResultsMocks[:len(_dat.NamedMixedTwoResultsMocks)-1]
		_dat.NamedMixedTwoResultsMocks = append(_dat.NamedMixedTwoResultsMocks, fn)
		_dat.NamedMixedTwoResultsMocks = append(_dat.NamedMixedTwoResultsMocks, fn)
	}
}

func (_recv *M0) _NamedMixedTwoResults_Stub() {
	_recv._NamedMixedTwoResults_Do(func(pkg.String, ...pkg.String) (r0 pkg.Int, r1 error) {
		return r0, r1
	})
}

func (_recv *M0) _NamedMixedTwoResults_Return(r0 pkg.Int, r1 error) {
	_recv._NamedMixedTwoResults_Do(func(pkg.String, ...pkg.String) (pkg.Int, error) {
		return r0, r1
	})
}

func (_recv *M0) _NamedMixedTwoResults_Calls() []_M0_NamedMixedTwoResults_Call {
	if _recv == nil {
		panic("M0.NamedMixedTwoResults: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	return _dat.NamedMixedTwoResultsCalls
}

func (_recv *M0) NamedParamNoResult(X pkg.String) {
	if _recv == nil {
		panic("M0.NamedParamNoResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	_dat.mutex.Lock()
	_dat.NamedParamNoResultCalls = append(_dat.NamedParamNoResultCalls, _M0_NamedParamNoResult_Call{X})
	_fn := _recv.T0.NamedParamNoResult
	if len(_dat.NamedParamNoResultMocks) > 0 {
		_fn = _dat.NamedParamNoResultMocks[0]
		if len(_dat.NamedParamNoResultMocks) > 1 {
			_dat.NamedParamNoResultMocks = _dat.NamedParamNoResultMocks[1:]
		}
	}
	_dat.mutex.Unlock()
	_fn(X)
}

func (_recv *M0) _NamedParamNoResult_Do(fn func(pkg.String) ()) {
	if _recv == nil {
		panic("M0.NamedParamNoResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	if fn == nil {
		_dat.NamedParamNoResultMocks = []func(pkg.String) (){}
	} else if len(_dat.NamedParamNoResultMocks) < 2 {
		_dat.NamedParamNoResultMocks = []func(pkg.String) (){fn, fn}
	} else {
		_dat.NamedParamNoResultMocks = _dat.NamedParamNoResultMocks[:len(_dat.NamedParamNoResultMocks)-1]
		_dat.NamedParamNoResultMocks = append(_dat.NamedParamNoResultMocks, fn)
		_dat.NamedParamNoResultMocks = append(_dat.NamedParamNoResultMocks, fn)
	}
}

func (_recv *M0) _NamedParamNoResult_Stub() {
	_recv._NamedParamNoResult_Do(func(pkg.String) () {
		return 
	})
}

func (_recv *M0) _NamedParamNoResult_Return() {
	_recv._NamedParamNoResult_Do(func(pkg.String) () {
		return 
	})
}

func (_recv *M0) _NamedParamNoResult_Calls() []_M0_NamedParamNoResult_Call {
	if _recv == nil {
		panic("M0.NamedParamNoResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	return _dat.NamedParamNoResultCalls
}

func (_recv *M0) NamedParamOneResult(X pkg.String) error {
	if _recv == nil {
		panic("M0.NamedParamOneResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	_dat.mutex.Lock()
	_dat.NamedParamOneResultCalls = append(_dat.NamedParamOneResultCalls, _M0_NamedParamOneResult_Call{X})
	_fn := _recv.T0.NamedParamOneResult
	if len(_dat.NamedParamOneResultMocks) > 0 {
		_fn = _dat.NamedParamOneResultMocks[0]
		if len(_dat.NamedParamOneResultMocks) > 1 {
			_dat.NamedParamOneResultMocks = _dat.NamedParamOneResultMocks[1:]
		}
	}
	_dat.mutex.Unlock()
	return _fn(X)
}

func (_recv *M0) _NamedParamOneResult_Do(fn func(pkg.String) (error)) {
	if _recv == nil {
		panic("M0.NamedParamOneResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	if fn == nil {
		_dat.NamedParamOneResultMocks = []func(pkg.String) (error){}
	} else if len(_dat.NamedParamOneResultMocks) < 2 {
		_dat.NamedParamOneResultMocks = []func(pkg.String) (error){fn, fn}
	} else {
		_dat.NamedParamOneResultMocks = _dat.NamedParamOneResultMocks[:len(_dat.NamedParamOneResultMocks)-1]
		_dat.NamedParamOneResultMocks = append(_dat.NamedParamOneResultMocks, fn)
		_dat.NamedParamOneResultMocks = append(_dat.NamedParamOneResultMocks, fn)
	}
}

func (_recv *M0) _NamedParamOneResult_Stub() {
	_recv._NamedParamOneResult_Do(func(pkg.String) (r0 error) {
		return r0
	})
}

func (_recv *M0) _NamedParamOneResult_Return(r0 error) {
	_recv._NamedParamOneResult_Do(func(pkg.String) (error) {
		return r0
	})
}

func (_recv *M0) _NamedParamOneResult_Calls() []_M0_NamedParamOneResult_Call {
	if _recv == nil {
		panic("M0.NamedParamOneResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	return _dat.NamedParamOneResultCalls
}

func (_recv *M0) NamedParamTwoResults(X pkg.String) (pkg.Int, error) {
	if _recv == nil {
		panic("M0.NamedParamTwoResults: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	_dat.mutex.Lock()
	_dat.NamedParamTwoResultsCalls = append(_dat.NamedParamTwoResultsCalls, _M0_NamedParamTwoResults_Call{X})
	_fn := _recv.T0.NamedParamTwoResults
	if len(_dat.NamedParamTwoResultsMocks) > 0 {
		_fn = _dat.NamedParamTwoResultsMocks[0]
		if len(_dat.NamedParamTwoResultsMocks) > 1 {
			_dat.NamedParamTwoResultsMocks = _dat.NamedParamTwoResultsMocks[1:]
		}
	}
	_dat.mutex.Unlock()
	return _fn(X)
}

func (_recv *M0) _NamedParamTwoResults_Do(fn func(pkg.String) (pkg.Int, error)) {
	if _recv == nil {
		panic("M0.NamedParamTwoResults: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	if fn == nil {
		_dat.NamedParamTwoResultsMocks = []func(pkg.String) (pkg.Int, error){}
	} else if len(_dat.NamedParamTwoResultsMocks) < 2 {
		_dat.NamedParamTwoResultsMocks = []func(pkg.String) (pkg.Int, error){fn, fn}
	} else {
		_dat.NamedParamTwoResultsMocks = _dat.NamedParamTwoResultsMocks[:len(_dat.NamedParamTwoResultsMocks)-1]
		_dat.NamedParamTwoResultsMocks = append(_dat.NamedParamTwoResultsMocks, fn)
		_dat.NamedParamTwoResultsMocks = append(_dat.NamedParamTwoResultsMocks, fn)
	}
}

func (_recv *M0) _NamedParamTwoResults_Stub() {
	_recv._NamedParamTwoResults_Do(func(pkg.String) (r0 pkg.Int, r1 error) {
		return r0, r1
	})
}

func (_recv *M0) _NamedParamTwoResults_Return(r0 pkg.Int, r1 error) {
	_recv._NamedParamTwoResults_Do(func(pkg.String) (pkg.Int, error) {
		return r0, r1
	})
}

func (_recv *M0) _NamedParamTwoResults_Calls() []_M0_NamedParamTwoResults_Call {
	if _recv == nil {
		panic("M0.NamedParamTwoResults: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	return _dat.NamedParamTwoResultsCalls
}

func (_recv *M0) OneNamedResult() error {
	if _recv == nil {
		panic("M0.OneNamedResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	_dat.mutex.Lock()
	_dat.OneNamedResultCalls = append(_dat.OneNamedResultCalls, _M0_OneNamedResult_Call{})
	_fn := _recv.T0.OneNamedResult
	if len(_dat.OneNamedResultMocks) > 0 {
		_fn = _dat.OneNamedResultMocks[0]
		if len(_dat.OneNamedResultMocks) > 1 {
			_dat.OneNamedResultMocks = _dat.OneNamedResultMocks[1:]
		}
	}
	_dat.mutex.Unlock()
	return _fn()
}

func (_recv *M0) _OneNamedResult_Do(fn func() (error)) {
	if _recv == nil {
		panic("M0.OneNamedResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	if fn == nil {
		_dat.OneNamedResultMocks = []func() (error){}
	} else if len(_dat.OneNamedResultMocks) < 2 {
		_dat.OneNamedResultMocks = []func() (error){fn, fn}
	} else {
		_dat.OneNamedResultMocks = _dat.OneNamedResultMocks[:len(_dat.OneNamedResultMocks)-1]
		_dat.OneNamedResultMocks = append(_dat.OneNamedResultMocks, fn)
		_dat.OneNamedResultMocks = append(_dat.OneNamedResultMocks, fn)
	}
}

func (_recv *M0) _OneNamedResult_Stub() {
	_recv._OneNamedResult_Do(func() (err error) {
		return err
	})
}

func (_recv *M0) _OneNamedResult_Return(err error) {
	_recv._OneNamedResult_Do(func() (error) {
		return err
	})
}

func (_recv *M0) _OneNamedResult_Calls() []_M0_OneNamedResult_Call {
	if _recv == nil {
		panic("M0.OneNamedResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	return _dat.OneNamedResultCalls
}

func (_recv *M0) OneParamNoResult(P0 pkg.String) {
	if _recv == nil {
		panic("M0.OneParamNoResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	_dat.mutex.Lock()
	_dat.OneParamNoResultCalls = append(_dat.OneParamNoResultCalls, _M0_OneParamNoResult_Call{P0})
	_fn := _recv.T0.OneParamNoResult
	if len(_dat.OneParamNoResultMocks) > 0 {
		_fn = _dat.OneParamNoResultMocks[0]
		if len(_dat.OneParamNoResultMocks) > 1 {
			_dat.OneParamNoResultMocks = _dat.OneParamNoResultMocks[1:]
		}
	}
	_dat.mutex.Unlock()
	_fn(P0)
}

func (_recv *M0) _OneParamNoResult_Do(fn func(pkg.String) ()) {
	if _recv == nil {
		panic("M0.OneParamNoResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	if fn == nil {
		_dat.OneParamNoResultMocks = []func(pkg.String) (){}
	} else if len(_dat.OneParamNoResultMocks) < 2 {
		_dat.OneParamNoResultMocks = []func(pkg.String) (){fn, fn}
	} else {
		_dat.OneParamNoResultMocks = _dat.OneParamNoResultMocks[:len(_dat.OneParamNoResultMocks)-1]
		_dat.OneParamNoResultMocks = append(_dat.OneParamNoResultMocks, fn)
		_dat.OneParamNoResultMocks = append(_dat.OneParamNoResultMocks, fn)
	}
}

func (_recv *M0) _OneParamNoResult_Stub() {
	_recv._OneParamNoResult_Do(func(pkg.String) () {
		return 
	})
}

func (_recv *M0) _OneParamNoResult_Return() {
	_recv._OneParamNoResult_Do(func(pkg.String) () {
		return 
	})
}

func (_recv *M0) _OneParamNoResult_Calls() []_M0_OneParamNoResult_Call {
	if _recv == nil {
		panic("M0.OneParamNoResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	return _dat.OneParamNoResultCalls
}

func (_recv *M0) OneParamOneResult(P0 pkg.String) error {
	if _recv == nil {
		panic("M0.OneParamOneResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	_dat.mutex.Lock()
	_dat.OneParamOneResultCalls = append(_dat.OneParamOneResultCalls, _M0_OneParamOneResult_Call{P0})
	_fn := _recv.T0.OneParamOneResult
	if len(_dat.OneParamOneResultMocks) > 0 {
		_fn = _dat.OneParamOneResultMocks[0]
		if len(_dat.OneParamOneResultMocks) > 1 {
			_dat.OneParamOneResultMocks = _dat.OneParamOneResultMocks[1:]
		}
	}
	_dat.mutex.Unlock()
	return _fn(P0)
}

func (_recv *M0) _OneParamOneResult_Do(fn func(pkg.String) (error)) {
	if _recv == nil {
		panic("M0.OneParamOneResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	if fn == nil {
		_dat.OneParamOneResultMocks = []func(pkg.String) (error){}
	} else if len(_dat.OneParamOneResultMocks) < 2 {
		_dat.OneParamOneResultMocks = []func(pkg.String) (error){fn, fn}
	} else {
		_dat.OneParamOneResultMocks = _dat.OneParamOneResultMocks[:len(_dat.OneParamOneResultMocks)-1]
		_dat.OneParamOneResultMocks = append(_dat.OneParamOneResultMocks, fn)
		_dat.OneParamOneResultMocks = append(_dat.OneParamOneResultMocks, fn)
	}
}

func (_recv *M0) _OneParamOneResult_Stub() {
	_recv._OneParamOneResult_Do(func(pkg.String) (r0 error) {
		return r0
	})
}

func (_recv *M0) _OneParamOneResult_Return(r0 error) {
	_recv._OneParamOneResult_Do(func(pkg.String) (error) {
		return r0
	})
}

func (_recv *M0) _OneParamOneResult_Calls() []_M0_OneParamOneResult_Call {
	if _recv == nil {
		panic("M0.OneParamOneResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	return _dat.OneParamOneResultCalls
}

func (_recv *M0) OneParamTwoResults(P0 pkg.String) (pkg.Int, error) {
	if _recv == nil {
		panic("M0.OneParamTwoResults: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	_dat.mutex.Lock()
	_dat.OneParamTwoResultsCalls = append(_dat.OneParamTwoResultsCalls, _M0_OneParamTwoResults_Call{P0})
	_fn := _recv.T0.OneParamTwoResults
	if len(_dat.OneParamTwoResultsMocks) > 0 {
		_fn = _dat.OneParamTwoResultsMocks[0]
		if len(_dat.OneParamTwoResultsMocks) > 1 {
			_dat.OneParamTwoResultsMocks = _dat.OneParamTwoResultsMocks[1:]
		}
	}
	_dat.mutex.Unlock()
	return _fn(P0)
}

func (_recv *M0) _OneParamTwoResults_Do(fn func(pkg.String) (pkg.Int, error)) {
	if _recv == nil {
		panic("M0.OneParamTwoResults: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	if fn == nil {
		_dat.OneParamTwoResultsMocks = []func(pkg.String) (pkg.Int, error){}
	} else if len(_dat.OneParamTwoResultsMocks) < 2 {
		_dat.OneParamTwoResultsMocks = []func(pkg.String) (pkg.Int, error){fn, fn}
	} else {
		_dat.OneParamTwoResultsMocks = _dat.OneParamTwoResultsMocks[:len(_dat.OneParamTwoResultsMocks)-1]
		_dat.OneParamTwoResultsMocks = append(_dat.OneParamTwoResultsMocks, fn)
		_dat.OneParamTwoResultsMocks = append(_dat.OneParamTwoResultsMocks, fn)
	}
}

func (_recv *M0) _OneParamTwoResults_Stub() {
	_recv._OneParamTwoResults_Do(func(pkg.String) (r0 pkg.Int, r1 error) {
		return r0, r1
	})
}

func (_recv *M0) _OneParamTwoResults_Return(r0 pkg.Int, r1 error) {
	_recv._OneParamTwoResults_Do(func(pkg.String) (pkg.Int, error) {
		return r0, r1
	})
}

func (_recv *M0) _OneParamTwoResults_Calls() []_M0_OneParamTwoResults_Call {
	if _recv == nil {
		panic("M0.OneParamTwoResults: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	return _dat.OneParamTwoResultsCalls
}

func (_recv *M0) OneResult() error {
	if _recv == nil {
		panic("M0.OneResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	_dat.mutex.Lock()
	_dat.OneResultCalls = append(_dat.OneResultCalls, _M0_OneResult_Call{})
	_fn := _recv.T0.OneResult
	if len(_dat.OneResultMocks) > 0 {
		_fn = _dat.OneResultMocks[0]
		if len(_dat.OneResultMocks) > 1 {
			_dat.OneResultMocks = _dat.OneResultMocks[1:]
		}
	}
	_dat.mutex.Unlock()
	return _fn()
}

func (_recv *M0) _OneResult_Do(fn func() (error)) {
	if _recv == nil {
		panic("M0.OneResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	if fn == nil {
		_dat.OneResultMocks = []func() (error){}
	} else if len(_dat.OneResultMocks) < 2 {
		_dat.OneResultMocks = []func() (error){fn, fn}
	} else {
		_dat.OneResultMocks = _dat.OneResultMocks[:len(_dat.OneResultMocks)-1]
		_dat.OneResultMocks = append(_dat.OneResultMocks, fn)
		_dat.OneResultMocks = append(_dat.OneResultMocks, fn)
	}
}

func (_recv *M0) _OneResult_Stub() {
	_recv._OneResult_Do(func() (r0 error) {
		return r0
	})
}

func (_recv *M0) _OneResult_Return(r0 error) {
	_recv._OneResult_Do(func() (error) {
		return r0
	})
}

func (_recv *M0) _OneResult_Calls() []_M0_OneResult_Call {
	if _recv == nil {
		panic("M0.OneResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	return _dat.OneResultCalls
}

func (_recv *M0) Simple() {
	if _recv == nil {
		panic("M0.Simple: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	_dat.mutex.Lock()
	_dat.SimpleCalls = append(_dat.SimpleCalls, _M0_Simple_Call{})
	_fn := _recv.T0.Simple
	if len(_dat.SimpleMocks) > 0 {
		_fn = _dat.SimpleMocks[0]
		if len(_dat.SimpleMocks) > 1 {
			_dat.SimpleMocks = _dat.SimpleMocks[1:]
		}
	}
	_dat.mutex.Unlock()
	_fn()
}

func (_recv *M0) _Simple_Do(fn func() ()) {
	if _recv == nil {
		panic("M0.Simple: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	if fn == nil {
		_dat.SimpleMocks = []func() (){}
	} else if len(_dat.SimpleMocks) < 2 {
		_dat.SimpleMocks = []func() (){fn, fn}
	} else {
		_dat.SimpleMocks = _dat.SimpleMocks[:len(_dat.SimpleMocks)-1]
		_dat.SimpleMocks = append(_dat.SimpleMocks, fn)
		_dat.SimpleMocks = append(_dat.SimpleMocks, fn)
	}
}

func (_recv *M0) _Simple_Stub() {
	_recv._Simple_Do(func() () {
		return 
	})
}

func (_recv *M0) _Simple_Return() {
	_recv._Simple_Do(func() () {
		return 
	})
}

func (_recv *M0) _Simple_Calls() []_M0_Simple_Call {
	if _recv == nil {
		panic("M0.Simple: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	return _dat.SimpleCalls
}

func (_recv *M0) TwoNamedResults() (pkg.Int, error) {
	if _recv == nil {
		panic("M0.TwoNamedResults: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	_dat.mutex.Lock()
	_dat.TwoNamedResultsCalls = append(_dat.TwoNamedResultsCalls, _M0_TwoNamedResults_Call{})
	_fn := _recv.T0.TwoNamedResults
	if len(_dat.TwoNamedResultsMocks) > 0 {
		_fn = _dat.TwoNamedResultsMocks[0]
		if len(_dat.TwoNamedResultsMocks) > 1 {
			_dat.TwoNamedResultsMocks = _dat.TwoNamedResultsMocks[1:]
		}
	}
	_dat.mutex.Unlock()
	return _fn()
}

func (_recv *M0) _TwoNamedResults_Do(fn func() (pkg.Int, error)) {
	if _recv == nil {
		panic("M0.TwoNamedResults: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	if fn == nil {
		_dat.TwoNamedResultsMocks = []func() (pkg.Int, error){}
	} else if len(_dat.TwoNamedResultsMocks) < 2 {
		_dat.TwoNamedResultsMocks = []func() (pkg.Int, error){fn, fn}
	} else {
		_dat.TwoNamedResultsMocks = _dat.TwoNamedResultsMocks[:len(_dat.TwoNamedResultsMocks)-1]
		_dat.TwoNamedResultsMocks = append(_dat.TwoNamedResultsMocks, fn)
		_dat.TwoNamedResultsMocks = append(_dat.TwoNamedResultsMocks, fn)
	}
}

func (_recv *M0) _TwoNamedResults_Stub() {
	_recv._TwoNamedResults_Do(func() (n pkg.Int, err error) {
		return n, err
	})
}

func (_recv *M0) _TwoNamedResults_Return(n pkg.Int, err error) {
	_recv._TwoNamedResults_Do(func() (pkg.Int, error) {
		return n, err
	})
}

func (_recv *M0) _TwoNamedResults_Calls() []_M0_TwoNamedResults_Call {
	if _recv == nil {
		panic("M0.TwoNamedResults: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	return _dat.TwoNamedResultsCalls
}

func (_recv *M0) TwoParamsNoResult(P0 pkg.String, P1 pkg.String) {
	if _recv == nil {
		panic("M0.TwoParamsNoResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	_dat.mutex.Lock()
	_dat.TwoParamsNoResultCalls = append(_dat.TwoParamsNoResultCalls, _M0_TwoParamsNoResult_Call{P0, P1})
	_fn := _recv.T0.TwoParamsNoResult
	if len(_dat.TwoParamsNoResultMocks) > 0 {
		_fn = _dat.TwoParamsNoResultMocks[0]
		if len(_dat.TwoParamsNoResultMocks) > 1 {
			_dat.TwoParamsNoResultMocks = _dat.TwoParamsNoResultMocks[1:]
		}
	}
	_dat.mutex.Unlock()
	_fn(P0, P1)
}

func (_recv *M0) _TwoParamsNoResult_Do(fn func(pkg.String, pkg.String) ()) {
	if _recv == nil {
		panic("M0.TwoParamsNoResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	if fn == nil {
		_dat.TwoParamsNoResultMocks = []func(pkg.String, pkg.String) (){}
	} else if len(_dat.TwoParamsNoResultMocks) < 2 {
		_dat.TwoParamsNoResultMocks = []func(pkg.String, pkg.String) (){fn, fn}
	} else {
		_dat.TwoParamsNoResultMocks = _dat.TwoParamsNoResultMocks[:len(_dat.TwoParamsNoResultMocks)-1]
		_dat.TwoParamsNoResultMocks = append(_dat.TwoParamsNoResultMocks, fn)
		_dat.TwoParamsNoResultMocks = append(_dat.TwoParamsNoResultMocks, fn)
	}
}

func (_recv *M0) _TwoParamsNoResult_Stub() {
	_recv._TwoParamsNoResult_Do(func(pkg.String, pkg.String) () {
		return 
	})
}

func (_recv *M0) _TwoParamsNoResult_Return() {
	_recv._TwoParamsNoResult_Do(func(pkg.String, pkg.String) () {
		return 
	})
}

func (_recv *M0) _TwoParamsNoResult_Calls() []_M0_TwoParamsNoResult_Call {
	if _recv == nil {
		panic("M0.TwoParamsNoResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	return _dat.TwoParamsNoResultCalls
}

func (_recv *M0) TwoParamsOneResult(P0 pkg.String, P1 pkg.String) error {
	if _recv == nil {
		panic("M0.TwoParamsOneResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	_dat.mutex.Lock()
	_dat.TwoParamsOneResultCalls = append(_dat.TwoParamsOneResultCalls, _M0_TwoParamsOneResult_Call{P0, P1})
	_fn := _recv.T0.TwoParamsOneResult
	if len(_dat.TwoParamsOneResultMocks) > 0 {
		_fn = _dat.TwoParamsOneResultMocks[0]
		if len(_dat.TwoParamsOneResultMocks) > 1 {
			_dat.TwoParamsOneResultMocks = _dat.TwoParamsOneResultMocks[1:]
		}
	}
	_dat.mutex.Unlock()
	return _fn(P0, P1)
}

func (_recv *M0) _TwoParamsOneResult_Do(fn func(pkg.String, pkg.String) (error)) {
	if _recv == nil {
		panic("M0.TwoParamsOneResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	if fn == nil {
		_dat.TwoParamsOneResultMocks = []func(pkg.String, pkg.String) (error){}
	} else if len(_dat.TwoParamsOneResultMocks) < 2 {
		_dat.TwoParamsOneResultMocks = []func(pkg.String, pkg.String) (error){fn, fn}
	} else {
		_dat.TwoParamsOneResultMocks = _dat.TwoParamsOneResultMocks[:len(_dat.TwoParamsOneResultMocks)-1]
		_dat.TwoParamsOneResultMocks = append(_dat.TwoParamsOneResultMocks, fn)
		_dat.TwoParamsOneResultMocks = append(_dat.TwoParamsOneResultMocks, fn)
	}
}

func (_recv *M0) _TwoParamsOneResult_Stub() {
	_recv._TwoParamsOneResult_Do(func(pkg.String, pkg.String) (r0 error) {
		return r0
	})
}

func (_recv *M0) _TwoParamsOneResult_Return(r0 error) {
	_recv._TwoParamsOneResult_Do(func(pkg.String, pkg.String) (error) {
		return r0
	})
}

func (_recv *M0) _TwoParamsOneResult_Calls() []_M0_TwoParamsOneResult_Call {
	if _recv == nil {
		panic("M0.TwoParamsOneResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	return _dat.TwoParamsOneResultCalls
}

func (_recv *M0) TwoParamsTwoResults(P0 pkg.String, P1 pkg.String) (pkg.Int, error) {
	if _recv == nil {
		panic("M0.TwoParamsTwoResults: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	_dat.mutex.Lock()
	_dat.TwoParamsTwoResultsCalls = append(_dat.TwoParamsTwoResultsCalls, _M0_TwoParamsTwoResults_Call{P0, P1})
	_fn := _recv.T0.TwoParamsTwoResults
	if len(_dat.TwoParamsTwoResultsMocks) > 0 {
		_fn = _dat.TwoParamsTwoResultsMocks[0]
		if len(_dat.TwoParamsTwoResultsMocks) > 1 {
			_dat.TwoParamsTwoResultsMocks = _dat.TwoParamsTwoResultsMocks[1:]
		}
	}
	_dat.mutex.Unlock()
	return _fn(P0, P1)
}

func (_recv *M0) _TwoParamsTwoResults_Do(fn func(pkg.String, pkg.String) (pkg.Int, error)) {
	if _recv == nil {
		panic("M0.TwoParamsTwoResults: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	if fn == nil {
		_dat.TwoParamsTwoResultsMocks = []func(pkg.String, pkg.String) (pkg.Int, error){}
	} else if len(_dat.TwoParamsTwoResultsMocks) < 2 {
		_dat.TwoParamsTwoResultsMocks = []func(pkg.String, pkg.String) (pkg.Int, error){fn, fn}
	} else {
		_dat.TwoParamsTwoResultsMocks = _dat.TwoParamsTwoResultsMocks[:len(_dat.TwoParamsTwoResultsMocks)-1]
		_dat.TwoParamsTwoResultsMocks = append(_dat.TwoParamsTwoResultsMocks, fn)
		_dat.TwoParamsTwoResultsMocks = append(_dat.TwoParamsTwoResultsMocks, fn)
	}
}

func (_recv *M0) _TwoParamsTwoResults_Stub() {
	_recv._TwoParamsTwoResults_Do(func(pkg.String, pkg.String) (r0 pkg.Int, r1 error) {
		return r0, r1
	})
}

func (_recv *M0) _TwoParamsTwoResults_Return(r0 pkg.Int, r1 error) {
	_recv._TwoParamsTwoResults_Do(func(pkg.String, pkg.String) (pkg.Int, error) {
		return r0, r1
	})
}

func (_recv *M0) _TwoParamsTwoResults_Calls() []_M0_TwoParamsTwoResults_Call {
	if _recv == nil {
		panic("M0.TwoParamsTwoResults: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	return _dat.TwoParamsTwoResultsCalls
}

func (_recv *M0) TwoResults() (pkg.Int, error) {
	if _recv == nil {
		panic("M0.TwoResults: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	_dat.mutex.Lock()
	_dat.TwoResultsCalls = append(_dat.TwoResultsCalls, _M0_TwoResults_Call{})
	_fn := _recv.T0.TwoResults
	if len(_dat.TwoResultsMocks) > 0 {
		_fn = _dat.TwoResultsMocks[0]
		if len(_dat.TwoResultsMocks) > 1 {
			_dat.TwoResultsMocks = _dat.TwoResultsMocks[1:]
		}
	}
	_dat.mutex.Unlock()
	return _fn()
}

func (_recv *M0) _TwoResults_Do(fn func() (pkg.Int, error)) {
	if _recv == nil {
		panic("M0.TwoResults: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	if fn == nil {
		_dat.TwoResultsMocks = []func() (pkg.Int, error){}
	} else if len(_dat.TwoResultsMocks) < 2 {
		_dat.TwoResultsMocks = []func() (pkg.Int, error){fn, fn}
	} else {
		_dat.TwoResultsMocks = _dat.TwoResultsMocks[:len(_dat.TwoResultsMocks)-1]
		_dat.TwoResultsMocks = append(_dat.TwoResultsMocks, fn)
		_dat.TwoResultsMocks = append(_dat.TwoResultsMocks, fn)
	}
}

func (_recv *M0) _TwoResults_Stub() {
	_recv._TwoResults_Do(func() (r0 pkg.Int, r1 error) {
		return r0, r1
	})
}

func (_recv *M0) _TwoResults_Return(r0 pkg.Int, r1 error) {
	_recv._TwoResults_Do(func() (pkg.Int, error) {
		return r0, r1
	})
}

func (_recv *M0) _TwoResults_Calls() []_M0_TwoResults_Call {
	if _recv == nil {
		panic("M0.TwoResults: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	return _dat.TwoResultsCalls
}

func (_recv *M0) VariadicNoResult(P0 ...pkg.String) {
	if _recv == nil {
		panic("M0.VariadicNoResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	_dat.mutex.Lock()
	_dat.VariadicNoResultCalls = append(_dat.VariadicNoResultCalls, _M0_VariadicNoResult_Call{P0})
	_fn := _recv.T0.VariadicNoResult
	if len(_dat.VariadicNoResultMocks) > 0 {
		_fn = _dat.VariadicNoResultMocks[0]
		if len(_dat.VariadicNoResultMocks) > 1 {
			_dat.VariadicNoResultMocks = _dat.VariadicNoResultMocks[1:]
		}
	}
	_dat.mutex.Unlock()
	_fn(P0...)
}

func (_recv *M0) _VariadicNoResult_Do(fn func(...pkg.String) ()) {
	if _recv == nil {
		panic("M0.VariadicNoResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	if fn == nil {
		_dat.VariadicNoResultMocks = []func(...pkg.String) (){}
	} else if len(_dat.VariadicNoResultMocks) < 2 {
		_dat.VariadicNoResultMocks = []func(...pkg.String) (){fn, fn}
	} else {
		_dat.VariadicNoResultMocks = _dat.VariadicNoResultMocks[:len(_dat.VariadicNoResultMocks)-1]
		_dat.VariadicNoResultMocks = append(_dat.VariadicNoResultMocks, fn)
		_dat.VariadicNoResultMocks = append(_dat.VariadicNoResultMocks, fn)
	}
}

func (_recv *M0) _VariadicNoResult_Stub() {
	_recv._VariadicNoResult_Do(func(...pkg.String) () {
		return 
	})
}

func (_recv *M0) _VariadicNoResult_Return() {
	_recv._VariadicNoResult_Do(func(...pkg.String) () {
		return 
	})
}

func (_recv *M0) _VariadicNoResult_Calls() []_M0_VariadicNoResult_Call {
	if _recv == nil {
		panic("M0.VariadicNoResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	return _dat.VariadicNoResultCalls
}

func (_recv *M0) VariadicOneResult(P0 ...pkg.String) error {
	if _recv == nil {
		panic("M0.VariadicOneResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	_dat.mutex.Lock()
	_dat.VariadicOneResultCalls = append(_dat.VariadicOneResultCalls, _M0_VariadicOneResult_Call{P0})
	_fn := _recv.T0.VariadicOneResult
	if len(_dat.VariadicOneResultMocks) > 0 {
		_fn = _dat.VariadicOneResultMocks[0]
		if len(_dat.VariadicOneResultMocks) > 1 {
			_dat.VariadicOneResultMocks = _dat.VariadicOneResultMocks[1:]
		}
	}
	_dat.mutex.Unlock()
	return _fn(P0...)
}

func (_recv *M0) _VariadicOneResult_Do(fn func(...pkg.String) (error)) {
	if _recv == nil {
		panic("M0.VariadicOneResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	if fn == nil {
		_dat.VariadicOneResultMocks = []func(...pkg.String) (error){}
	} else if len(_dat.VariadicOneResultMocks) < 2 {
		_dat.VariadicOneResultMocks = []func(...pkg.String) (error){fn, fn}
	} else {
		_dat.VariadicOneResultMocks = _dat.VariadicOneResultMocks[:len(_dat.VariadicOneResultMocks)-1]
		_dat.VariadicOneResultMocks = append(_dat.VariadicOneResultMocks, fn)
		_dat.VariadicOneResultMocks = append(_dat.VariadicOneResultMocks, fn)
	}
}

func (_recv *M0) _VariadicOneResult_Stub() {
	_recv._VariadicOneResult_Do(func(...pkg.String) (r0 error) {
		return r0
	})
}

func (_recv *M0) _VariadicOneResult_Return(r0 error) {
	_recv._VariadicOneResult_Do(func(...pkg.String) (error) {
		return r0
	})
}

func (_recv *M0) _VariadicOneResult_Calls() []_M0_VariadicOneResult_Call {
	if _recv == nil {
		panic("M0.VariadicOneResult: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	return _dat.VariadicOneResultCalls
}

func (_recv *M0) VariadicTwoResults(P0 ...pkg.String) (pkg.Int, error) {
	if _recv == nil {
		panic("M0.VariadicTwoResults: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	_dat.mutex.Lock()
	_dat.VariadicTwoResultsCalls = append(_dat.VariadicTwoResultsCalls, _M0_VariadicTwoResults_Call{P0})
	_fn := _recv.T0.VariadicTwoResults
	if len(_dat.VariadicTwoResultsMocks) > 0 {
		_fn = _dat.VariadicTwoResultsMocks[0]
		if len(_dat.VariadicTwoResultsMocks) > 1 {
			_dat.VariadicTwoResultsMocks = _dat.VariadicTwoResultsMocks[1:]
		}
	}
	_dat.mutex.Unlock()
	return _fn(P0...)
}

func (_recv *M0) _VariadicTwoResults_Do(fn func(...pkg.String) (pkg.Int, error)) {
	if _recv == nil {
		panic("M0.VariadicTwoResults: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	if fn == nil {
		_dat.VariadicTwoResultsMocks = []func(...pkg.String) (pkg.Int, error){}
	} else if len(_dat.VariadicTwoResultsMocks) < 2 {
		_dat.VariadicTwoResultsMocks = []func(...pkg.String) (pkg.Int, error){fn, fn}
	} else {
		_dat.VariadicTwoResultsMocks = _dat.VariadicTwoResultsMocks[:len(_dat.VariadicTwoResultsMocks)-1]
		_dat.VariadicTwoResultsMocks = append(_dat.VariadicTwoResultsMocks, fn)
		_dat.VariadicTwoResultsMocks = append(_dat.VariadicTwoResultsMocks, fn)
	}
}

func (_recv *M0) _VariadicTwoResults_Stub() {
	_recv._VariadicTwoResults_Do(func(...pkg.String) (r0 pkg.Int, r1 error) {
		return r0, r1
	})
}

func (_recv *M0) _VariadicTwoResults_Return(r0 pkg.Int, r1 error) {
	_recv._VariadicTwoResults_Do(func(...pkg.String) (pkg.Int, error) {
		return r0, r1
	})
}

func (_recv *M0) _VariadicTwoResults_Calls() []_M0_VariadicTwoResults_Call {
	if _recv == nil {
		panic("M0.VariadicTwoResults: nil pointer receiver")
	}
	_dat := _M0PtrData(_recv)
	defer _dat.mutex.Unlock()
	_dat.mutex.Lock()
	return _dat.VariadicTwoResultsCalls
}
